# # -*-python-*-

# import os
# -*-python-*-

import os

Import("env")
pyenv = env.Clone(tools = ['boost_python'],
                LIBS  = ['basic'])

exclude = """
""".split()

sources = [source for source in pyenv.Glob('*.*') if source.name not in exclude]

targets = pyenv.BuildBoostPython("basic/__basic", sources)
Alias("py", targets)
Alias("build", targets)