##################################################################################
#                                                                                #
# AutoWIG: Automatic Wrapper and Interface Generator                             #
#                                                                                #
# Homepage: http://autowig.readthedocs.io                                        #
#                                                                                #
# Copyright (c) 2016 Pierre Fernique                                             #
#                                                                                #
# This software is distributed under the CeCILL-C license. You should have       #
# received a copy of the legalcode along with this work. If not, see             #
# <http://www.cecill.info/licences/Licence_CeCILL-C_V1-en.html>.                 #
#                                                                                #
# File authors: Pierre Fernique <pfernique@gmail.com> (2)                        #
#                                                                                #
##################################################################################

package:
    name: python-basic
    version: "1.0.0"

source:
    path: ../..
  
build:
    number: 0
    script: 
        - scons py --prefix={{ PREFIX }} -j{{ CPU_COUNT }} # [unix]
        - scons py --prefix={{ LIBRARY_PREFIX }} -j{{ CPU_COUNT }} # [win]
        - python setup.py install

about:
    home: http://autowig.readthedocs.io/
    license: CeCILL-C

requirements:
    build:
        - scons
        - libboost
        - libbasic
    run:
        - libboost
        - libbasic