package:
  name: python-basic
  version: "1.0.0"

source:
  path: ../..
  
build:
  number: 0
  script: 
    - scons py --prefix={{ PREFIX }} -j{{ CPU_COUNT }}
    - python setup.py install

about:
  home: http://autowig.readthedocs.io/
  license: CeCILL-C

requirements:
  build:
    - scons
    - libboost
    - libbasic
  run:
    - libboost
    - libbasic