pylint:
  disable:
    - protected-access
    - too-many-branches
    - function-redefined
    - too-many-statements
    - too-many-locals
    - too-many-arguments
    - bare-except
mccabe:
  disable:
    - MC0001
pyflakes:
  disable:
    - F812
