##################################################################################
#                                                                                #
# AutoWIG: Automatic Wrapper and Interface Generator                             #
#                                                                                #
# Homepage: http://autowig.readthedocs.io                                        #
#                                                                                #
# Copyright (c) 2016 Pierre Fernique                                             #
#                                                                                #
# This software is distributed under the CeCILL-C license. You should have       #
# received a copy of the legalcode along with this work. If not, see             #
# <http://www.cecill.info/licences/Licence_CeCILL-C_V1-en.html>.                 #
#                                                                                #
# File authors: Pierre Fernique <pfernique@gmail.com> (6)                        #
#                                                                                #
##################################################################################

test-warnings: true
pylint:
  disable:
    - protected-access
    - too-many-branches
    - function-redefined
    - too-many-statements
    - too-many-locals
    - too-many-arguments
    - bare-except
mccabe:
  disable:
    - MC0001
pyflakes:
  disable:
    - F812
