about:
  authors:
  - Pierre Fernique
  - Christophe Pradal
  brief: 
  email: statiskit@googlegroups.com
  name: AutoWIG
  package: autowig
  version: 1.0.0
authors:
  basename: AUTHORS.rst
  format: '* {name} <{email}> ({score})'
  plugin: commit
license:
  basename: LICENSE.rst
  plugin: CeCILL-C
  width: 78
version:
  plugin: semantic
