##################################################################################
#                                                                                #
# AutoWIG: Automatic Wrapper and Interface Generator                             #
#                                                                                #
# Homepage: http://autowig.readthedocs.io                                        #
#                                                                                #
# Copyright (c) 2016 Pierre Fernique                                             #
#                                                                                #
# This software is distributed under the CeCILL-C license. You should have       #
# received a copy of the legalcode along with this work. If not, see             #
# <http://www.cecill.info/licences/Licence_CeCILL-C_V1-en.html>.                 #
#                                                                                #
# File authors: Pierre Fernique <pfernique@gmail.com> (2)                        #
#                                                                                #
##################################################################################

about:
  authors:
  - Pierre Fernique
  - Christophe Pradal
  brief: !!python/unicode 'Automatic Wrapper and Interface Generator'
  email: !!python/unicode 'statiskit@googlegroups.com'
  homepage: http://autowig.readthedocs.io
  name: !!python/unicode 'AutoWIG'
  plugin: github
  version: v1.0.0
authors:
  basename: CONTRIBUTORS.rst
  format: '* `{name} <{email}>`_ ({score})'
  plugin: commit
license:
  basename: LICENSE.rst
  exclude:
  - ./.git/*
  - ./build/*
  plugin: CeCILL-C
  width: 78
