sudo: required

services:
  - docker

before_install:
    - docker pull statiskit/ubuntu
    - docker run -it statiskit/ubuntu
    - ls
    - cd ~
    


script:
  - conda build conda/python-autowig -c statiskit -c conda-forge --no-test
  - conda install python-autowig -c statiskit -c conda-forge --use-local
  - python setup.py develop --user
  - conda install python-clanglite -c statiskit
  - pip install nose
  - nosetests test -v --with-coverage --cover-package=autowig

after_success:
  - clang++ -x c++ -v -E /dev/null
  - coveralls
  - coveralls debug
  - if [[ "$TRAVIS_BRANCH" = "master" ]] && [[ "$TRAVIS_PULL_REQUEST" = "false" ]]; then
      conda install anaconda-client;
      anaconda login --username ${ANACONDA_USERNAME%%} --password ${ANACONDA_PASSWORD%%};
      CONDA_FILE=`conda build conda/python-autowig --output`; 
      anaconda upload --user ${ANACONDA_CHANNEL%%} ${CONDA_FILE%%};
    fi
