sudo: required
dist: trusty
language: cpp

os: linux

before_install:
    - if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      elif [[ "$TRAVIS_OS_NAME" = "osx" ]]; then
        curl https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -o miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - export LD_LIBRARY_PATH=$HOME/miniconda/lib:$LD_LIBRARY_PATH
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
    - conda install conda-build

install:
    - pip install coverage
    - pip install coveralls
    - pip install nose
    
before_script:
  - conda build conda/python-clang -c statiskit -c conda-forge --no-test
  - conda build conda/python-autowig -c statiskit -c conda-forge --no-test
  - conda install python-autowig -c statiskit -c conda-forge --use-local
  - conda remove python-autowig

script:
  - python setup.py develop --user
  - conda install python-clanglite -c statiskit
  - conda install gitpython -c conda-forge
  - conda install scons -c statiskit
  - cd doc/basic
  - P=`python -c 'import autowig; print autowig.__path__[0]'`
  - coverage run --source=$P $HOME/miniconda/bin/scons
  - cd ../..
  - nosetests test -v --with-coverage
  - coverage combine .coverage doc/basic/.coverage

after_success:
  - coveralls
  - if [[ "$TRAVIS_BRANCH" = "master" ]] && [[ "$TRAVIS_PULL_REQUEST" = "false" ]]; then
      conda install anaconda-client;
      anaconda login --username ${ANACONDA_USERNAME%%} --password ${ANACONDA_PASSWORD%%};
      CONDA_FILE=`conda build conda/python-clanglite --output`; 
      anaconda upload --user ${ANACONDA_CHANNEL%%} ${CONDA_FILE%%} --force;
      CONDA_FILE=`conda build conda/python-autowig --output`; 
      anaconda upload --user ${ANACONDA_CHANNEL%%} ${CONDA_FILE%%} --force;
    fi
