##################################################################################
#                                                                                #
# AutoWIG: Automatic Wrapper and Interface Generator                             #
#                                                                                #
# Homepage: http://autowig.readthedocs.io                                        #
#                                                                                #
# Copyright (c) 2016 Pierre Fernique                                             #
#                                                                                #
# This software is distributed under the CeCILL-C license. You should have       #
# received a copy of the legalcode along with this work. If not, see             #
# <http://www.cecill.info/licences/Licence_CeCILL-C_V1-en.html>.                 #
#                                                                                #
# File authors: Pierre Fernique <pfernique@gmail.com> (82)                       #
#                                                                                #
##################################################################################

sudo: required
dist: trusty
language: cpp

os: linux

before_install:
    - if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      elif [[ "$TRAVIS_OS_NAME" = "osx" ]]; then
        curl https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -o miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - export LD_LIBRARY_PATH=$HOME/miniconda/lib:$LD_LIBRARY_PATH
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
    - conda install conda-build

install:
    - conda install curl
    - pip install coverage
    - pip install coveralls
    - pip install nose

script:
  - bash conda/build.sh

after_success:
  - coveralls
  - if [[ "$TRAVIS_BRANCH" = "master" ]] && [[ "$TRAVIS_PULL_REQUEST" = "false" ]]; then
      if [[ ! -z $ANACONDA_USERNAME ]] && [[ ! -z $ANACONDA_PASSWORD ]]; then
        conda install anaconda-client;
        anaconda login --username "$ANACONDA_USERNAME" --password "$ANACONDA_PASSWORD";
        for CONDA_RECIPE in python-clang python-autowig; do
            CONDA_FILE=`conda build conda/$CONDA_RECIPE --output`; 
            anaconda upload --user statiskit ${CONDA_FILE%%} --force;
        done;
      fi
      if [[ ! -z $DOCKER_USERNAME ]] && [[ ! -z $DOCKER_PASSWORD ]]; then
        docker build -t statiskit/autowig .;
        docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        docker push statiskit/autowig;
      fi
      curl --request POST http://readthedocs.org/build/autowig;
    fi
