platform:
  - x86
  - x64

environment:
  matrix:
    - RECIPE: ..\doc\examples\basic\conda\libbasic
    - RECIPE: ..\doc\examples\basic\conda\python-basic
    - RECIPE: python-autowig

install:
  - git clone https://github.com/StatisKit/appveyor-ci.git appveyor-ci
  - cd appveyor-ci
  - call install.bat
    
before_build:
  - call before_build.bat

build_script:
  - call build_script.bat
  
after_build:
  - call after_build.bat

deploy:
  provider: Script
  on:
    branch: master
 
before_deploy:
  - call before_deploy.bat

deploy_script:
  - call deploy_script.bat

after_deploy:
  - call after_deploy.bat

on_success:
  - call on_success.bat

on_failure:
  - call on_failure.bat

on_finish:
  - call on_finish.bat