import os
from distutils import sysconfig
import sys

AddOption('--prefix',
  dest='prefix',
  type='string',
  nargs=1,
  action='store',
  metavar='DIR',
  help='installation prefix',
  default=sys.prefix)

AddOption('--parser',
    dest='parser',
    type='string',
    nargs=1,
    action='store',
    help='AutoWIG parser plugin',
    default='libclang')

AddOption('--controller',
    dest='controller',
    type='string',
    nargs=1,
    action='store',
    help='AutoWIG controller plugin',
    default='default')

AddOption('--generator',
    dest='generator',
    type='string',
    nargs=1,
    action='store',
    help='AutoWIG generator plugin',
    default='boost_python_internal')

variables = Variables()

env = Environment(PREFIX = GetOption('prefix'),
                  autowig_parser = GetOption('parser'),
                  autowig_controller = GetOption('controller'),
                  autowig_generator = GetOption('generator'))
variables.Update(env)

env.AppendUnique(LIBS = ['boost_python', 'python' + sysconfig.get_python_version()])
env.AppendUnique(CPPPATH = [sysconfig.get_python_inc()])
env.AppendUnique(CPPDEFINES = ['BOOST_PYTHON_DYNAMIC_LIB'])

env.Prepend(CPPPATH='$PREFIX/include')
env.Prepend(LIBPATH='$PREFIX/lib')


env.AppendUnique(CXXFLAGS = ['-x', 'c++',
                             '-std=c++0x',
                             '-Wwrite-strings'])

VariantDir('build', 'src')
SConscript(os.path.join('build', 'cpp', 'SConscript'), exports="env")
SConscript(os.path.join('build', 'py', 'SConscript'), exports="env")