## Copyright [2017-2018] UMR MISTEA INRA, UMR LEPSE INRA,                ##
##                       UMR AGAP CIRAD, EPI Virtual Plants Inria        ##
## Copyright [2015-2016] UMR AGAP CIRAD, EPI Virtual Plants Inria        ##
##                                                                       ##
## This file is part of the AutoWIG project. More information can be     ##
## found at                                                              ##
##                                                                       ##
##     http://autowig.rtfd.io                                            ##
##                                                                       ##
## The Apache Software Foundation (ASF) licenses this file to you under  ##
## the Apache License, Version 2.0 (the "License"); you may not use this ##
## file except in compliance with the License. You should have received  ##
## a copy of the Apache License, Version 2.0 along with this file; see   ##
## the file LICENSE. If not, you may obtain a copy of the License at     ##
##                                                                       ##
##     http://www.apache.org/licenses/LICENSE-2.0                        ##
##                                                                       ##
## Unless required by applicable law or agreed to in writing, software   ##
## distributed under the License is distributed on an "AS IS" BASIS,     ##
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or       ##
## mplied. See the License for the specific language governing           ##
## permissions and limitations under the License.                        ##

package:
  name: autowig-toolchain
  version: {{ DATETIME_DESCRIBE_VERSION }}

build:
  number: {{ DATETIME_DESCRIBE_NUMBER }}

about:
  home: http://autowig.readthedocs.org
  license: Apache License 2.0
  summary: Automatic Wrapper and Interface Generator

requirements:
  build:
    - libboost-dev
    - libboost_python
    - libpybind11-dev
    - python-pybind11
    - python-autowig
    - libtoolchain
    - python-toolchain
    - python-clanglite
  host:
    - python
  run:
    - {{ pin_compatible('libboost-dev', exact=True) }}
    - {{ pin_compatible('libboost_python', exact=True) }}
    - {{ pin_compatible('libpybind11-dev', exact=True) }}
    - {{ pin_compatible('python-pybind11', exact=True) }}
    - {{ pin_compatible('python-autowig', exact=True) }}
    - {{ pin_compatible('libtoolchain', exact=True) }}
    - {{ pin_compatible('python-toolchain', exact=True) }}
    - {{ pin_compatible('python-clanglite', exact=True) }}
    - python