name: autowig_doc
channels:
 - defaults
 - statiskit
 - conda-forge
dependencies:
 - python-autowig
 - python-clanglite
 - python-scons
 - gitpython
 - jupyter
 - sphinx
 - pip:
   - nbsphinx
   - sphinxcontrib-bibtex
