#include <clang/AST/ExternalASTSource.h>
#include <clang/AST/DependentDiagnostic.h>
#include <clang/AST/ParentMap.h>
#include <clang/AST/DeclGroup.h>
#include <clang/AST/DeclAccessPair.h>
#include <clang/AST/UnresolvedSet.h>
#include <clang/AST/DeclarationName.h>
#include <clang/AST/Stmt.h>
#include <clang/AST/Redeclarable.h>
#include <clang/AST/Type.h>
#include <clang/AST/SelectorLocationsKind.h>
#include <clang/AST/ExprObjC.h>
#include <clang/AST/OperationKinds.h>
#include <clang/AST/DeclObjC.h>
#include <clang/AST/CXXInheritance.h>
#include <clang/AST/CommentLexer.h>
#include <clang/AST/ASTTypeTraits.h>
#include <clang/AST/TemplateBase.h>
#include <clang/AST/DeclFriend.h>
#include <clang/AST/OpenMPClause.h>
#include <clang/AST/DeclLookups.h>
#include <clang/AST/StmtVisitor.h>
#include <clang/AST/VTableBuilder.h>
#include <clang/AST/ASTUnresolvedSet.h>
#include <clang/AST/GlobalDecl.h>
#include <clang/AST/DeclBase.h>
#include <clang/AST/ASTContext.h>
#include <clang/AST/CharUnits.h>
#include <clang/AST/StmtOpenMP.h>
#include <clang/AST/TypeLocVisitor.h>
#include <clang/AST/LambdaCapture.h>
#include <clang/AST/CanonicalType.h>
#include <clang/AST/PrettyPrinter.h>
#include <clang/AST/CommentCommandTraits.h>
#include <clang/AST/NestedNameSpecifier.h>
#include <clang/AST/DeclTemplate.h>
#include <clang/AST/Mangle.h>
#include <clang/AST/StmtIterator.h>
#include <clang/AST/Attr.h>
#include <clang/AST/StmtGraphTraits.h>
#include <clang/AST/MangleNumberingContext.h>
#include <clang/AST/StmtCXX.h>
#include <clang/AST/CommentSema.h>
#include <clang/AST/RecursiveASTVisitor.h>
#include <clang/AST/ASTConsumer.h>
#include <clang/AST/ASTFwd.h>
#include <clang/AST/TypeLoc.h>
#include <clang/AST/CommentDiagnostic.h>
#include <clang/AST/VTTBuilder.h>
#include <clang/AST/EvaluatedExprVisitor.h>
#include <clang/AST/CommentParser.h>
#include <clang/AST/AttrIterator.h>
#include <clang/AST/DataRecursiveASTVisitor.h>
#include <clang/AST/NSAPI.h>
#include <clang/AST/TypeOrdering.h>
#include <clang/AST/TypeVisitor.h>
#include <clang/AST/Decl.h>
#include <clang/AST/ExprCXX.h>
#include <clang/AST/CommentVisitor.h>
#include <clang/AST/ASTDiagnostic.h>
#include <clang/AST/AST.h>
#include <clang/AST/ASTLambda.h>
#include <clang/AST/StmtObjC.h>
#include <clang/AST/RecordLayout.h>
#include <clang/AST/APValue.h>
#include <clang/AST/DeclContextInternals.h>
#include <clang/AST/TemplateName.h>
#include <clang/AST/ASTImporter.h>
#include <clang/AST/DeclOpenMP.h>
#include <clang/AST/ASTMutationListener.h>
#include <clang/AST/RawCommentList.h>
#include <clang/AST/ASTVector.h>
#include <clang/AST/Comment.h>
#include <clang/AST/DeclCXX.h>
#include <clang/AST/CommentBriefParser.h>
#include <clang/AST/Expr.h>
#include <clang/AST/BaseSubobject.h>
#include <clang/AST/DeclVisitor.h>
#include <clang/Frontend/ASTUnit.h>

namespace autowig
{
    unsigned int get_nb_decls(const clang::DeclContext& context);
    
    clang::Decl* get_attr(const clang::DeclContext& context, const unsigned int& decl);
}
