package:
  name: libbasic
  version: "1.0.0"

source:
  path: ../..

build:
  number: 0
  script: scons cpp --prefix={{ PREFIX }} -j{{ CPU_COUNT }}

about:
  home: http://autowig.readthedocs.io/
  license: CeCILL-C

requirements:
  build:
    - scons
    - libboost
  run:
    - libboost