# -*-python-*-

import os
import platform

system = platform.system().lower()

Import("env")

cppenv = env.Clone(tools = ['cpp'])

cppenv.AppendUnique(CPPDEFINES = ['LIBBASIC'])

exclude = """
""".split()

sources = [source for source in cppenv.Glob('*.h*') if not source.name in exclude]
targets = cppenv.CppDev("basic", sources)
Alias("cpp-dev", targets)
Alias("cpp", targets)
Alias("install", targets)

exclude = """
""".split()

sources = [source for source in cppenv.Glob('*.cpp') if not source.name in exclude]
targets = cppenv.CppLib("basic", sources)
Alias("cpp-lib", targets)
Alias("cpp", targets)
Alias("install", targets)