# -*-python-*-

import os
import platform

system = platform.system().lower()

Import("env")

cppenv = env.Clone(tools = ['cpp'],
                   CPPDEFINES = ['LIBBASIC'])

exclude = """
""".split()

sources = [source for source in cppenv.Glob('*.*') if not source.name in exclude]

targets = cppenv.BuildCpp("basic", sources)
Alias("cpp", targets)
Alias("build", targets)