# -*-python-*-

import os

Import("env")

cppenv = env.Clone()

cppenv.AppendUnique(CPPDEFINES = ['BUILD_LIBCLANGLITE'])

headers = cppenv.Glob('*.h*')
includes = cppenv.Install(os.path.join(cppenv['PREFIX'], "include", "basic"), headers)
Alias("cpp", includes)
Alias("build", includes)

sources = cppenv.Glob('*.cpp')
if cppenv.get("static"):
    lib = cppenv.StaticLibrary(os.path.join(cppenv['PREFIX'], "lib", "basic"), sources)
else:
    lib = cppenv.SharedLibrary(os.path.join(cppenv['PREFIX'], "lib", "basic"), sources)
Alias("cpp", lib)
Alias("build", lib)