package:
  name: python-autowig
  version: "1.0.0"

source:
  path: ../..

build:
  number: 0
  script: python setup.py install

about:
  home: http://autowig.readthedocs.org
  license: CeCILL-C

requirements:
  build:
    - python
    - pyyaml
  run:
    - python
    - mako
    - dateutil
    - python-parse
    - pygments
    - pypandoc
    - path.py
    - python-clang
    - python-git
    - numpy
    - python-pkgtk

test:
   requires:
     - nose
     - coverage
     - python-clanglite
     - gitpython
     - python-scons
   commands:
     - cd {{ SRC_DIR }}
     - nosetests test --pdb -x -s -v --with-coverage --cover-tests --cover-package=autowig --cover-package=test
     - sed -i -e 's#'"$PREFIX"'/python2.7/site-packages#'"$RECIPE_DIR"'../../src/py#g'
     - mv .coverage {{ RECIPE_DIR }}/../../
