##################################################################################
#                                                                                #
# AutoWIG: Automatic Wrapper and Interface Generator                             #
#                                                                                #
# Homepage: http://autowig.readthedocs.io                                        #
#                                                                                #
# Copyright (c) 2016 Pierre Fernique                                             #
#                                                                                #
# This software is distributed under the CeCILL license. You should have       #
# received a copy of the legalcode along with this work. If not, see             #
# <http://www.cecill.info/licences/Licence_CeCILL_V2.1-en.html>.                 #
#                                                                                #
# File authors: Pierre Fernique <pfernique@gmail.com> (43)                       #
#                                                                                #
##################################################################################

package:
  name: python-autowig
  version: "1.0.0"

source:
  path: ../..
  patches:            [not linux]
    - windows.patch   [win]
    - osx.patch       [osx]

build:
  number: 0
  script:
    - python setup.py install
    - mkdir $SP_DIR/autowig/site_autowig                                                               [not win]
    - mkdir -p $SP_DIR/SCons/site_scons/site_tools                                                     [not win]
    - cp $RECIPE_DIR/autowig.py  $SP_DIR/SCons/site_scons/site_tools/autowig.py                        [not win]
    - if not exist %SP_DIR%\AutoWIG\site_autowig mkdir %SP_DIR%\SCons\site_autowig                     [win]
    - if not exist %SP_DIR%\SCons\site_scons\site_tools mkdir %SP_DIR%\SCons\site_scons\site_tools     [win]
    - copy %RECIPE_DIR%\autowig.py %SP_DIR%\SCons\site_scons\site_tools\autowig.py                     [win]

about:
  home: http://autowig.readthedocs.org
  license: CeCILL

requirements:
  build:
    - python
    - python-dev
    - python-pkg
  run:
    - python
    - mako
    - python-dateutil
    - python-parse
    - pygments
    - pypandoc
    - path.py
    - python-clang
    - numpy
    - python-pkg

test:
  source_files:
    - test/test_basic.py
    - doc
    - src
  requires:
    - libdev
    - python-dev
    - python-dbg
    - python-clanglite
    - gitpython
    - libboost
  commands:
    - conda build doc/examples/basic/conda/libbasic -c statiskit -c conda-forge
    - conda install libbasic --use-local -c statiskit -c conda-forge
    - nosetests test -x -s -v --with-coverage --cover-tests --cover-package=autowig --cover-package=test --nocapture
    # - cd {{ RECIPE_DIR }}
    # - cd ..
    # - cd ..
    # - REPOSITORY_DIR=`pwd`                                                                          [unix]
    # - nosetests test -x -s -v --with-coverage --cover-tests --cover-package=autowig --cover-package=test --nocapture
    # - sed -i -e 's#'"$PREFIX"'/lib/python2.7/site-packages#'"$REPOSITORY_DIR"'/src/py#g' .coverage  [unix]
    # - sed -i -e 's#'"$SRC_DIR"'#'"$REPOSITORY_DIR"'#g' .coverage                                    [unix]
    # - mv .coverage $REPOSITORY_DIR                                                                  [unix]
