##################################################################################
#                                                                                #
# AutoWIG: Automatic Wrapper and Interface Generator                             #
#                                                                                #
# Homepage: http://autowig.readthedocs.io                                        #
#                                                                                #
# Copyright (c) 2016 Pierre Fernique                                             #
#                                                                                #
# This software is distributed under the CeCILL-C license. You should have       #
# received a copy of the legalcode along with this work. If not, see             #
# <http://www.cecill.info/licences/Licence_CeCILL-C_V1-en.html>.                 #
#                                                                                #
# File authors: Pierre Fernique <pfernique@gmail.com> (43)                       #
#                                                                                #
##################################################################################

package:
  name: python-autowig
  version: "1.0.0"

source:
  path: ../..

build:
  number: 0
  script: python setup.py install

about:
  home: http://autowig.readthedocs.org
  license: CeCILL-C

requirements:
  build:
    - python
    - pyyaml
    - python-pkgtk
  run:
    - python
    - mako
    - dateutil
    - python-parse
    - pygments
    - pypandoc
    - path.py
    - python-clang
    - python-git
    - numpy
    - python-pkgtk

test:
   requires:
     - nose
     - coverage
     - python-clanglite # [not win]
     - pytthon-gitpython
     - python-scons
   commands:
     - cd {{ SRC_DIR }}
     - nosetests test --pdb -x -s -v --with-coverage --cover-tests --cover-package=autowig --cover-package=test
     - REPOSITORY_DIR=`readlink -e $RECIPE_DIR/../..`
     - sed -i -e 's#'"$PREFIX"'/lib/python2.7/site-packages#'"$REPOSITORY_DIR"'/src/py#g' .coverage
     - sed -i -e 's#'"$SRC_DIR"'#'"$REPOSITORY_DIR"'#g' .coverage
     - mv .coverage $REPOSITORY_DIR
