package:
  name: python-autowig
  version: "1.0.0"

source:
  path: ../..

build:
  number: 0
  script: python setup.py install

about:
  home: http://autowig.readthedocs.org
  license: CeCILL-C

requirements:
  build:
    - python
    - pyyaml
  run:
    - python
    - mako
    - dateutil
    - python-parse
    - pygments
    - pypandoc
    - path.py

test:
   requires:
     - nose
     - coverage
     - libclang
     - python-clanglite
   commands:
     - echo {{ environ.get('TRAVIS_BUILD_DIR', '') }}
     - if [[ $TRAVIS_BUILD_DIR ]]; then
         echo "travis";
       else
         echo "not travis";
       fi
     - nosetests {{ SRC_DIR }} -v --with-coverage --cover-package=autowig
