##################################################################################
#                                                                                #
# AutoWIG: Automatic Wrapper and Interface Generator                             #
#                                                                                #
# Homepage: http://autowig.readthedocs.io                                        #
#                                                                                #
# Copyright (c) 2016 Pierre Fernique                                             #
#                                                                                #
# This software is distributed under the CeCILL license. You should have       #
# received a copy of the legalcode along with this work. If not, see             #
# <http://www.cecill.info/licences/Licence_CeCILL_V2.1-en.html>.                 #
#                                                                                #
# File authors: Pierre Fernique <pfernique@gmail.com> (43)                       #
#                                                                                #
##################################################################################

package:
  name: python-autowig
  version: "1.0.0"

source:
  path: ../..
  patches: # [not linux]
    - windows.patch # [win]
    - macosx.patch # [osx]
    
build:
  number: 0


about:
  home: http://autowig.readthedocs.org
  license: CeCILL

requirements:
  build:
    - py-build
  run:
    - py-run
    - mako
    - python-dateutil
    - python-parse
    - pygments
    - pypandoc
    - path.py
    - python-clang
    - numpy
    - python-pkgtk

test:
   requires:
     - cpp-build
     - py-build
     - python-clanglite                 [unix]
     - gitpython
     - python-scons
     - libbasic
     - libboost
   commands:
     - cd {{ RECIPE_DIR }}
     - cd ..
     - cd ..
     - REPOSITORY_DIR=`pwd`                                                                          [unix]
     - nosetests test -x -s -v --with-coverage --cover-tests --cover-package=autowig --cover-package=test --nocapture
     - sed -i -e 's#'"$PREFIX"'/lib/python2.7/site-packages#'"$REPOSITORY_DIR"'/src/py#g' .coverage  [unix]
     - sed -i -e 's#'"$SRC_DIR"'#'"$REPOSITORY_DIR"'#g' .coverage                                    [unix]
     - mv .coverage $REPOSITORY_DIR                                                                  [unix]
