package:
  name: python-autowig
  version: "1.0.0"

source:
  path: ../..

build:
  number: 0
  script: python setup.py install

about:
  home: http://autowig.readthedocs.org
  license: CeCILL-C

requirements:
  build:
    - python
    - pyyaml
  run:
    - python
    - mako
    - dateutil
    - python-parse
    - pygments
    - pypandoc
    - path.py
    - python-clang
    - python-git
    - numpy

test:
   requires:
     - nose
     - coverage
     - python-clanglite
     - gitpython
   commands:
     - nosetests {{ SRC_DIR }} -v --with-coverage --cover-package=autowig
