##################################################################################
#                                                                                #
# AutoWIG: Automatic Wrapper and Interface Generator                             #
#                                                                                #
# Homepage: http://autowig.readthedocs.io                                        #
#                                                                                #
# Copyright (c) 2016 Pierre Fernique                                             #
#                                                                                #
# This software is distributed under the CeCILL license. You should have       #
# received a copy of the legalcode along with this work. If not, see             #
# <http://www.cecill.info/licences/Licence_CeCILL_V2.1-en.html>.                 #
#                                                                                #
# File authors: Pierre Fernique <pfernique@gmail.com> (43)                       #
#                                                                                #
##################################################################################

package:
  name: python-autowig
  version: "1.0.0"

source:
  path: ../..
  patches:            [not linux]
    - windows.patch   [win]
    - osx.patch       [osx]

build:
  number: 0

about:
  home: http://autowig.readthedocs.org
  license: CeCILL

requirements:
  build:
    - python
    - python-dev
    - python-pkg
  run:
    - python
    - mako
    - python-dateutil
    - python-parse
    - pygments
    - pypandoc
    - path.py
    - python-clang
    - numpy
    - python-pkg

test:
  source_files:
    - test
    - doc
    - src
  requires:
    - libdev
    - python-dev
    - python-dbg
    - clang                  [win]
    - python-clanglite       [unix]
    - gitpython
    - libboost
  commands:
    - nosetests test -x -s -v --with-coverage --cover-tests --cover-package=autowig --cover-package=test --nocapture