# -*-python-*-

import os

pj = os.path.join

SConsignFile()

env = Environment()
env.Append(CPPPATH = ['binomial'])
env.AppendUnique(CXXFLAGS=['-x', 'c++', "-std=c++0x"])

# Build stage
SConscript(pj("binomial/SConscript"), exports="env")

Default("build")
