package:
  name: python-autowig
  version: "1.0.0"

source:
  path: ../../..

build:
  number: 0

about:
  home: http://autowig.readthedocs.org
  license: Apache License 2.0
  summary: Automatic Wrapper and Interface Generator

requirements:
  build:
    - python
    - python-toolchain
  run:
    - python
    - mako
    - python-dateutil
    - python-parse
    - pygments
    - pandoc
    - pypandoc
    - path.py
    - numpy

test:
  source_files:
    - test
    - doc
    - src
  requires:
    - python
    - libtoolchain
    - python-toolchain
    - clang
    - python-clanglite
    - git
    - gitpython
    - libboost
  commands:
   - nosetests test -x -s -v -A "level <= {{ environ.get('TEST_LEVEL', 1) }} and linux" [linux]
   - nosetests test -x -s -v -A "level <= {{ environ.get('TEST_LEVEL', 1) }} and osx"   [osx]
   - nosetests test -x -s -v -A "level <= {{ environ.get('TEST_LEVEL', 1) }} and win"   [win]
