# This file has been automatically generated by pkg_builder

from openalea.core import *

__name__ = 'autowig'
__version__ = '1.0.0'
__license__ = 'CeCILL-C'
__author__ = None
__institutes__ = None
__description__ = ''
__url__ = 'http://openalea.gforge.inria.fr'

__editable__ = 'True'
__icon__ = ''
__alias__ = []

__all__ = []


    

